add_newline = false


[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 80
style = "bold red"

[username]
show_always = true

[status]
disabled = false
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
style = "bg:yellow"

[hostname]
disabled=false
ssh_only = false
format =  "on [$hostname](yellow) "

[jobs]
symbol = "+ "
threshold = 1
format = "[$symbol$number]($style) "
